version: '3.2'

services:

  postgres:
      image: postgres:10
      container_name: gateway_postgres
      volumes:
        - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
        - "dbdata:/var/lib/postgresql/data"
      environment:
        - POSTGRES_USER=${DATABASE_USERNAME}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_DB=${DATABASE_NAME}
      ports:
        - ${DATABASE_PORT}:${DATABASE_PORT}
      networks:
        - finteh-network

  gateway:
    build: .
    container_name: gateway
    volumes:
      - ./:/app
    command: >
      bash -c "pipenv run alembic upgrade head
      && pipenv run python . "
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    expose:
      - "${HTTP_PORT}"
    depends_on:
      - postgres
    networks:
      - finteh-network

volumes:
  dbdata:

networks:
  finteh-network:
    external: true
